Make phone number None by default in add_mail_contact()
This is necessary if e-mail is used from stdin. Without that:

TypeError: add_mail_contact() missing 1 required positional argument: 'phone'